routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/index');
});

Route::get('/index','FrontendController@index');
Route::get('/detail/category/{id}','FrontendController@detailCategory')->name('detail_category');
Route::get('/detail/catalog/{id}','FrontendController@detailCatalog')->name('detail_catalog');
Route::get('/search/','FrontendController@search')->name('search');

Auth::routes(['verify' => true]);
Route::get('/register', function() {
    return redirect('/login');
});
Route::group(['middleware' => ['auth','verified']], function() {
	Route::get('/home', 'HomeController@index')->name('home');

	Route::group(['middleware' => 'can:update-profile,id'], function() {
	    Route::get('profile/users/{id}','UserController@show')->name('profile.show');
		Route::get('profile/users/{id}/edit','UserController@edit')->name('profile.edit');
		Route::match(['put', 'patch'],'profile/users/{id}','UserController@update')->name('profile.update');
    });

	Route::group(['middleware' => 'can:isAdmin'], function() {
		Route::resource('users', 'UserController');
		Route::resource('roles', 'RoleController');
		Route::resource('categories', 'CategoryController');
		Route::resource('metadata', 'MetadataController');
		Route::resource('katalogMetadatas', 'KatalogMetadataController');
		Route::put('catalogs/category/{id}','CatalogController@updateStatus')->name('catalogs.update_status');
		Route::post('users/import','UserController@import')->name('users.import');
	});
	
	Route::resource('catalogs', 'CatalogController');
	Route::resource('catalogMetadataValues', 'CatalogMetadataValueController');
	Route::get('catalogs/category/{id}', 'CatalogController@indexWithCategory')->name('catalogs.index_with_category');
	Route::get('catalogs/create/category/{id}', 'CatalogController@createWithCategory')->name('catalogs.create_with_category');
	Route::get('report/index','ReportController@index')->name('report.index');
});

app/Models/CatalogMetadataValue.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class CatalogMetadataValue
 * @package App\Models
 * @version September 8, 2020, 2:14 pm UTC
 *
 * @property \App\Models\Catalog $catalog
 * @property \App\Models\Metadata $metadata
 * @property integer $catalog_id
 * @property integer $metadata_id
 * @property string $value
 */
class CatalogMetadataValue extends Model
{
    use SoftDeletes;

    public $table = 'catalog_metadata_value';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'catalog_id',
        'metadata_id',
        'metadata_key',
        'value'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'catalog_id' => 'integer',
        'metadata_id' => 'integer',
        'metadata_key' => 'string',
        'value' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'catalog_id' => 'required',
        'metadata_id' => 'required',
        'metadata_key' => 'required',
        'value' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function catalog()
    {
        return $this->belongsTo(\App\Models\Catalog::class, 'catalog_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function metadata()
    {
        return $this->belongsTo(\App\Models\Metadata::class, 'metadata_id');
    }
}

app/Http/Controllers/CatalogMetadataValueController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\CatalogMetadataValueDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCatalogMetadataValueRequest;
use App\Http\Requests\UpdateCatalogMetadataValueRequest;
use App\Repositories\CatalogMetadataValueRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class CatalogMetadataValueController extends AppBaseController
{
    /** @var  CatalogMetadataValueRepository */
    private $catalogMetadataValueRepository;

    public function __construct(CatalogMetadataValueRepository $catalogMetadataValueRepo)
    {
        $this->catalogMetadataValueRepository = $catalogMetadataValueRepo;
    }

    /**
     * Display a listing of the CatalogMetadataValue.
     *
     * @param CatalogMetadataValueDataTable $catalogMetadataValueDataTable
     * @return Response
     */
    public function index(CatalogMetadataValueDataTable $catalogMetadataValueDataTable)
    {
        return $catalogMetadataValueDataTable->render('catalog_metadata_values.index');
    }

    /**
     * Show the form for creating a new CatalogMetadataValue.
     *
     * @return Response
     */
    public function create()
    {
        return view('catalog_metadata_values.create');
    }

    /**
     * Store a newly created CatalogMetadataValue in storage.
     *
     * @param CreateCatalogMetadataValueRequest $request
     *
     * @return Response
     */
    public function store(CreateCatalogMetadataValueRequest $request)
    {
        $input = $request->all();

        $catalogMetadataValue = $this->catalogMetadataValueRepository->create($input);

        Flash::success('Catalog Metadata Value saved successfully.');

        return redirect(route('catalogMetadataValues.index'));
    }

    /**
     * Display the specified CatalogMetadataValue.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $catalogMetadataValue = $this->catalogMetadataValueRepository->find($id);

        if (empty($catalogMetadataValue)) {
            Flash::error('Catalog Metadata Value not found');

            return redirect(route('catalogMetadataValues.index'));
        }

        return view('catalog_metadata_values.show')->with('catalogMetadataValue', $catalogMetadataValue);
    }

    /**
     * Show the form for editing the specified CatalogMetadataValue.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $catalogMetadataValue = $this->catalogMetadataValueRepository->find($id);

        if (empty($catalogMetadataValue)) {
            Flash::error('Catalog Metadata Value not found');

            return redirect(route('catalogMetadataValues.index'));
        }

        return view('catalog_metadata_values.edit')->with('catalogMetadataValue', $catalogMetadataValue);
    }

    /**
     * Update the specified CatalogMetadataValue in storage.
     *
     * @param  int              $id
     * @param UpdateCatalogMetadataValueRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCatalogMetadataValueRequest $request)
    {
        $catalogMetadataValue = $this->catalogMetadataValueRepository->find($id);

        if (empty($catalogMetadataValue)) {
            Flash::error('Catalog Metadata Value not found');

            return redirect(route('catalogMetadataValues.index'));
        }

        $catalogMetadataValue = $this->catalogMetadataValueRepository->update($request->all(), $id);

        Flash::success('Catalog Metadata Value updated successfully.');

        return redirect(route('catalogMetadataValues.index'));
    }

    /**
     * Remove the specified CatalogMetadataValue from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $catalogMetadataValue = $this->catalogMetadataValueRepository->find($id);

        if (empty($catalogMetadataValue)) {
            Flash::error('Catalog Metadata Value not found');

            return redirect(route('catalogMetadataValues.index'));
        }

        $this->catalogMetadataValueRepository->delete($id);

        Flash::success('Catalog Metadata Value deleted successfully.');

        return redirect(route('catalogMetadataValues.index'));
    }
}

resources/views/catalog_metadata_values/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('catalogMetadataValues.index') !!}">Catalog Metadata Value</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Catalog Metadata Value</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'catalogMetadataValues.store']) !!}

                                   @include('catalog_metadata_values.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/catalog_metadata_values/datatables_actions.blade.php
{!! Form::open(['route' => ['catalogMetadataValues.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('catalogMetadataValues.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('catalogMetadataValues.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/catalog_metadata_values/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('catalogMetadataValues.index') !!}">Catalog Metadata Value</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Catalog Metadata Value</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($catalogMetadataValue, ['route' => ['catalogMetadataValues.update', $catalogMetadataValue->id], 'method' => 'patch']) !!}

                              @include('catalog_metadata_values.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/catalog_metadata_values/fields.blade.php
<!-- Catalog Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('catalog_id', 'Catalog Id:') !!}
    {!! Form::number('catalog_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Metadata Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('metadata_id', 'Metadata Id:') !!}
    {!! Form::number('metadata_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('catalogMetadataValues.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/catalog_metadata_values/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Catalog Metadata Values</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             CatalogMetadataValues
                             <a class="pull-right" href="{{ route('catalogMetadataValues.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('catalog_metadata_values.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/catalog_metadata_values/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('catalogMetadataValues.index') }}">Catalog Metadata Value</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('catalogMetadataValues.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('catalog_metadata_values.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/catalog_metadata_values/show_fields.blade.php
<!-- Catalog Id Field -->
<div class="form-group">
    {!! Form::label('catalog_id', 'Catalog Id:') !!}
    <p>{{ $catalogMetadataValue->catalog_id }}</p>
</div>

<!-- Metadata Id Field -->
<div class="form-group">
    {!! Form::label('metadata_id', 'Metadata Id:') !!}
    <p>{{ $catalogMetadataValue->metadata_id }}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{{ $catalogMetadataValue->value }}</p>
</div>

resources/views/catalog_metadata_values/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush